### ISSUE TITLE
On/Off button

### ISSUE THREAD

**Issue by mdaquin** [afel-project/browsing-history-webext#4]
Make it easier to stop the tracking and start it. Can/should be added as part of the popup page with clicking on the icon, and should change the icon showing when it is "recording".

**Comment by alexdma** [comment]
I see that pressing the OFF button deletes all user keys from storage. This means that if I press the ON button I will have to re-authenticate with the platform. It might be a little annoying, do you want this?

Alternatively we could have a separate command for that, such as "de-authorise this browser". I can use it to keep the extension installed but only running from certain machines.

**Comment by alexdma** [comment]
Agreed that re-login will be required when reactivating the monitor.
