### ISSUE TITLE
Option to upload last few days of browsing on sign up

### ISSUE THREAD

**Issue by mdaquin** [afel-project/browsing-history-webext#7]
Ask if the use wants there last few days of browsing to be included, so they don't start from scratch.
Need a mechanism to collect the last few days of browsing and submit them. Will need to extend the API to allow batch submission of activities.

**Comment by alexdma** [comment]
As a workaround, the extension currently uploads up to the last 1,000 visits present in the local history, but one by one (i.e. with up to 1,000 calls upon pressing the button).

To make this better, the server API could support POSTing of bulk data about multiple visits.

**Comment by alexdma** [comment]
Open new issue for bulk upload.
